- hosts: all
  tasks:
    - name: Install Nginx latest Version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: copy the configuration file
      copy:
        src: nginx-cfg/nginx.conf
        dest: /etc/nginx/sites-enabled/default
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes    


  